spring:
  application:
    name: orderitem-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true 
      path: /h2 
  datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver 
      username: sa
      password:  
      
         
server:
   port: 8082
 
eureka:
  client:
    service-url:
      defaulltZone : http://localhost:8761/eureka
    instance:
     preferIpAddress: true
     fetchregistry: true   
 
  
  
    
